name: laoma_tingshu
description: LaoMa Pro Audio Book Final Version
publish_to: 'none'
version: 2.1.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1 # 联网搜资源
  html: ^0.15.3 # 解析搜索结果
  webview_flutter: ^4.2.2 # 内置纯净播放窗口
  url_launcher: ^6.1.11 # 唤起外部链接能力
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true
