name: laoma_tingshu
description: Real Audio Book App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11  # 关键：有了它才能跳到网页听书
flutter:
  uses-material-design: true
